apiVersion: v1
kind: Service
metadata:
  name: restaurant-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: restaurant-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
