trigger:
  - main

pool:
  name: Default

variables:
  imageRepository: 'restaurant-frontend'
  dockerfilePath: 'docker/Dockerfile'
  buildContext: '.'
  tag: '$(Build.BuildId)'
  acrLoginServer: 'srujanatfacr001.azurecr.io'
  kubernetesNamespace: 'default'

stages:
  - stage: Build_and_Push
    displayName: Build and Push Docker Image
    jobs:
      - job: Build
        displayName: Build React App and Push Image
        steps:
          - task: NodeTool@0
            displayName: Install Node.js
            inputs:
              versionSpec: '18.x'

          - script: |
              cd app
              npm install
              npm run build
            displayName: Build React application

          - task: Docker@2
            displayName: Build and push image to ACR
            inputs:
              containerRegistry: 'azure-acr-connection'
              repository: '$(imageRepository)'
              command: 'buildAndPush'
              Dockerfile: '$(dockerfilePath)'
              buildContext: '$(buildContext)'
              tags: |
                $(tag)

  - stage: Deploy_to_AKS
    displayName: Deploy to AKS
    dependsOn: Build_and_Push
    jobs:
      - job: Deploy
        displayName: Deploy Kubernetes Manifests
        steps:
          - script: |
              sed "s|IMAGE_PLACEHOLDER|$(acrLoginServer)/$(imageRepository):$(tag)|g" k8s/deployment.yml > k8s/deployment-rendered.yml
            displayName: Render Kubernetes deployment manifest

          - task: KubernetesManifest@1
            displayName: Deploy application to AKS
            inputs:
              action: 'deploy'
              connectionType: 'azureResourceManager'
              azureSubscriptionConnection: 'azure-rm-connection'
              azureResourceGroup: 'tf-devops-rg'
              kubernetesCluster: 'tf-restaurant-aks'
              namespace: '$(kubernetesNamespace)'
              manifests: |
                k8s/deployment-rendered.yml
                k8s/service.yml